### ISSUE TITLE
Crashes with NoSuchMethodError on block update

### ISSUE THREAD

**Issue by copygirl** [BRForgers/Ducts#2]
**Minecraft:** `1.16.2`
**Fabric API:** `0.1.3+12a8474cfa`
**Ducts:** `1.0.1`
(And plenty of other mods. Full list can be seen in the crash report.)

Crashes both client and server with the following error seemingly on a block update:

```
java.lang.NoSuchMethodError: net.minecraft.class_1936.method_8410()Lnet/minecraft/class_1937;
	at br.com.brforgers.mods.ducts.blocks.DuctBlock.method_9559(DuctBlock.java:91)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:910)
	at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:852)
	at net.minecraft.class_1937.method_30092(class_1937.java:265)
	[...]
```

**Full crash report:** https://paste.ee/p/hhRmf

**Comment by BrekiTomasson** [comment]
After more than a month of waiting for this issue to be fixed, I'm kind of giving up hope, so I've forked this repo and will be working on fixing it myself.

**Comment by BrekiTomasson** [comment]
@copygirl Fixed the bug and upped dependencies to 1.16.3.  Enjoy: https://github.com/BrekiTomasson/Ducts/releases/tag/v1.0.2

Will also be making a pull request to this repository, but I can see that one has already been made with essentially the same fix, and that hasn't been merged, so I believe the author(s) of this mod have given up on it.

**Comment by allanf181** [comment]
https://www.curseforge.com/minecraft/mc-mods/ducts/files/3112010

**Comment by BrekiTomasson** [comment]
Lovely! Thanks for the official update, now I can replace my fork :)
